---
plugins:
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0
  # enable detailed explanations available in cops
  # the default output is not enough to understand what is wrong
  DisplayCopNames: true
  ExtraDetails: true
  DisplayStyleGuide: true
  Exclude:
    - "exe/rokujo-extract"
    - "vendor/**/*"

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/SymbolArray:
  # perefer brackets for `grep-ability`
  EnforcedStyle: brackets

Style/FrozenStringLiteralComment:
  Enabled: true

Layout/LineLength:
  Exclude: []
  # ignore heredoc for readability
  AllowHeredoc: true
  # URLs are almost always long
  AllowURI: true
  URISchemes:
    - http
    - https
    - git
    - ftp
  IgnoreCopDirectives: true

RSpec/ExampleLength:
  CountAsOne:
    - array
    - hash
    - heredoc
RSpec/NestedGroups:
  # accept one more depth for contexts in spec files.
  Max: 4
Metrics/MethodLength:
  CountAsOne:
    - array
    - hash
    - heredoc
    - method_call
