#!/usr/bin/env ruby
# frozen_string_literal: true

require "rokujo/extractor"
require "rokujo/extractor/formatters"
require "rokujo/extractor/concerns/renderable"
require "thor"
require "json"
require "ruby-spacy"

module Rokujo
  module Extractor
    # A simple CLI for Rokujo::Extractor
    class CLI < Thor
      include Rokujo::Extractor::Concerns::Renderable

      attr_reader :errors

      def self.exit_on_failure? = true

      map %w[--version -v] => :version, %w[--help -h] => :show_help
      desc "--version, -v", "Print the version"
      def version
        puts(Rokujo::Extractor::VERSION)
      end

      desc "--help, -h", "Print help"
      def show_help
        help
      end

      desc "extract FILE [FILE ...]", "Extract sentences from file(s) (.pdf, .docx, .txt)"
      method_option :format, aliases: "-f", default: "text", desc: "Output format: text or json"
      method_option :uuid, type: :string, default: "file", enum: %w[file record],
                           desc: "Generate UUID per record or per file (.jsonl file only)"
      method_option :progress, type: :boolean, default: true, desc: "Show progress."
      default_task :extract

      # rubocop:disable Metrics/MethodLength
      # TODO: create a wrapper to perform slow operation and display a spinner
      def extract(*file_paths)
        show_help_and_exit if file_paths.empty?

        self.widget_enable = options[:progress] ? true : false
        @model = with_spinner do
          Spacy::Language.new(Rokujo::Extractor::Parsers::Base::DEFAULT_SPACY_MODEL_NAME)
        end

        file_paths.each do |path|
          results = extract_sentences(path)
          extract_show results
        end
        return unless errors&.any?

        errors.each { |e| warn e }
        exit 1
      end
      # rubocop:enable Metrics/MethodLength

      # rubocop:disable Metrics/BlockLength
      # The block is for non-command methods
      no_commands do
        def extract_sentences(path)
          extractor = Rokujo::Extractor.create(path,
                                               model: @model,
                                               metadata: { source: File.basename(path) },
                                               uuid: options[:uuid],
                                               widget_enable: options[:progress])
          extractor.extract_sentences
        rescue StandardError => e
          add_error "Error processing #{path}: #{e.class}\n#{e.message}\n#{e.backtrace.join("\n")}"
          nil
        end

        def extract_show(results)
          return unless results

          case options[:format]
          when "json"
            formatter = Rokujo::Extractor::Formatters::JSONL.new
          when "text"
            formatter = Rokujo::Extractor::Formatters::Text.new
          when "csv"
            formatter = Rokujo::Extractor::Formatters::CSV.new
          end
          puts formatter.call(results, widget_enable: options[:progress])
        end

        def show_help_and_exit
          help
          exit
        end

        def add_error(error)
          @errors ||= []
          @errors << error
        end
      end
      # rubocop:enable Metrics/BlockLength
    end
  end
end

unless Rokujo::Extractor::CLI.all_tasks.key?(ARGV[0]) || Rokujo::Extractor::CLI.instance_variable_get(:@map).key?(ARGV[0])
  ARGV.unshift(Rokujo::Extractor::CLI.default_task)
end
Rokujo::Extractor::CLI.start(ARGV)
